#!/usr/bin/env python3
"""Render Android's destination matcher from the reviewed bridge numbering snapshot.

No network access. To update, review the pinned upstream US fixedLine/mobile
patterns and replace server/bridge/us_nanp.json, then run this script.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
value = json.loads((ROOT / 'server/bridge/us_nanp.json').read_text())
pattern = value['pattern']
assert '"' not in pattern and '\n' not in pattern
(ROOT / 'app/src/main/java/dev/r1ptt/bridge/BridgeDestinations.kt').write_text(
    '// Generated by tools/sync-bridge-numbering.py; do not edit.\n'
    '// Copyright The Libphonenumber Authors. Apache-2.0; see third_party/libphonenumber.\n'
    '// Source revision: ' + value['commit'] + '\n'
    'package dev.r1ptt.bridge\n\n'
    'internal val supportedUsNumber = Regex("""' + pattern + '""")\n')
